#!/bin/bash -x

rm db.sqlite3

git checkout -- */migrations
git clean -fxd */migrations

./manage.py makemigrations
./manage.py migrate
export DJANGO_SUPERUSER_USERNAME=proton
export DJANGO_SUPERUSER_PASSWORD=feisuzhu
./manage.py createsuperuser --email proton@proton.moe --noinput
./manage.py loaddata page game-{collection,card,character,spellcard,other}
