#!/bin/bash -x

cd $(dirname $0)

./manage.py flush --no-input
export DJANGO_SUPERUSER_USERNAME=proton
export DJANGO_SUPERUSER_PASSWORD=feisuzhu
./manage.py createsuperuser --email proton@proton.moe --noinput
./manage.py loaddata page game-{collection,card,character,spellcard,others}
