# Generated by Django 4.1.7 on 2023-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="episode",
        ),
        migrations.AddField(
            model_name="episode",
            name="versions",
            field=models.ManyToManyField(
                help_text="卡牌版本",
                related_name="episodes",
                to="game.version",
                verbose_name="卡牌版本",
            ),
        ),
    ]
