# Generated by Django 4.1.7 on 2023-03-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spellcard",
            name="lsc",
            field=models.BooleanField(default=False, help_text="终符", verbose_name="终符"),
        ),
    ]
