# Generated by Django 4.1.4 on 2023-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infoblock",
            name="content",
        ),
        migrations.RemoveField(
            model_name="infoblockbutton",
            name="icon",
        ),
        migrations.AlterField(
            model_name="infoblock",
            name="category",
            field=models.CharField(
                choices=[("COMMUNITY", "社群"), ("SHOP", "商店"), ("DECK_SHARE", "卡组分享")],
                help_text="分类",
                max_length=50,
                verbose_name="分类",
            ),
        ),
    ]
